name: CHERIoT Network-Stack HIL-CI

on:
  workflow_run:
    workflows: ["CHERIoT Network-Stack CI"]
    types: [completed]
  workflow_dispatch:
    inputs:
      run-id:
        description: 'main.yml workflow run ID to download firmware from'
        type: string
        required: true

jobs:
  hardware-test:
    name: Hardware Test on Sonata
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ the-capable-hub-farm, board:Sonata ]
    environment: hil-hardware # Requires you to create this environment in settings
    permissions:
      statuses: write
      actions: read
      contents: read
    
    steps:
    - name: Set PR status to pending
      if: github.event_name == 'workflow_run'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.workflow_run.head_sha,
            state: 'pending',
            context: 'HIL Tests (Sonata)',
            description: 'Awaiting hardware testing...'
          })

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download firmware artifacts
      uses: actions/download-artifact@v4
      with:
        name: sonata-firmware
        path: firmware
        run-id: ${{ github.event_name == 'workflow_dispatch' && inputs.run-id || github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Mount Sonata
      run: |
        # Mount the SONATA at a known location
        sudo mkdir -p /mnt/SONATA
        sudo mount -o uid=$(id -u),gid=$(id -g),rw -L SONATA /mnt/SONATA

        # Store mount point for all subsequent steps
        echo "MOUNT_POINT=/mnt/SONATA" >> $GITHUB_ENV

    - name: Make sure the board is not in reset
      run: sudo usbrelay HURTM_1=0

    - name: Clean existing firmware
      run: rm -f "$MOUNT_POINT"/*.uf2

    - name: Flash and test all examples
      run: bash .github/sonata-hil/run-hil-tests.sh

    - name: Update PR status
      if: always() && github.event_name == 'workflow_run'
      uses: actions/github-script@v7
      with:
        script: |
          const state = '${{ job.status }}' === 'success' ? 'success' : 'failure';
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.workflow_run.head_sha,
            state: state,
            context: 'HIL Tests (Sonata)',
            description: `Hardware tests finished with status: ${state}`
          })
